services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
  app:
    image: avi-order:latest
    restart: always
    ports:
      - ${HTTP_PORT}:8080
      - ${HTTPS_PORT}:8443
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_INIT: ${DB_INIT}
      KEYSTORE_PASSWORD: ${KEYSTORE_PASSWORD}
      spring_profiles_active: ${spring_profiles_active}
