- name: Run using a project directory
  hosts: localhost
  become: true
  tasks:
    - name: Tear down db container
      community.docker.docker_compose_v2:
        project_src: ../../docker
        env_files: ./dev.env
        state: absent
        services:
          - db
    - name: build new db container
      community.docker.docker_compose_v2:
        project_src: ../../docker
        env_files: ./dev.env
        services:
          - db