alter table if exists advertisements drop constraint if exists FKklqx7hdgyk17oftwha23x7wcu;
alter table if exists orders drop constraint if exists FK32ql8ubntj5uh44ph9659tiih;
alter table if exists user_role drop constraint if exists FKj345gk1bovqvfame88rcx7yyx;

drop table if exists advertisements cascade;
drop table if exists orders cascade;
drop table if exists user_role cascade;
drop table if exists users cascade;

create table advertisements (product_factor_count_per_day integer not null, promote_contacts boolean not null, promotion_end_date DATE not null, promotion_start_date DATE not null, id bigint generated by default as identity, order_id uuid not null, link varchar(255) not null, primary key (id));
create table orders (creation_time timestamp(6) with time zone not null, recent_edit_time timestamp(6) with time zone not null, user_id bigint not null, id uuid not null, name varchar(255) not null, primary key (id));
create table user_role (roles smallint check (roles between 0 and 2), user_id bigint not null);
create table users (creation_time timestamp(6) with time zone not null, id bigint generated by default as identity, password varchar(255) not null, username varchar(255) not null unique, primary key (id));

alter table if exists advertisements add constraint FKklqx7hdgyk17oftwha23x7wcu foreign key (order_id) references orders;
alter table if exists orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users;
alter table if exists user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users;
